name: Publish artifacts

on:
  push:
    branches:
      - master

concurrency: ci-${{ github.ref_name }}
env:
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  publish-docker:
    name: Publish Docker image 
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        kubectl-version: [v1.26.14,v1.27.11]
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Prepare repository name
      id: prepare-repository-name
      run: |
        repository=$REGISTRY/${{ github.repository }}
        echo "repository=${repository,,}" >> $GITHUB_OUTPUT
  
    - name: Extract metadata (tags, labels) for Docker
      id: extract-metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ steps.prepare-repository-name.outputs.repository }}
  
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        file: Dockerfile
        cache-from: |
          type=gha,scope=sha-${{ github.sha }}
          type=gha,scope=${{ github.ref_name }}
        cache-to: |
          type=gha,scope=sha-${{ github.sha }},mode=max
          type=gha,scope=${{ github.ref_name }},mode=max
        push: true
        build-args: |
          "KUBECTL_VERSION=${{ matrix.kubectl-version }}"
        tags: "${{ steps.prepare-repository-name.outputs.repository }}:${{ matrix.kubectl-version }}"
        
  